apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: backend-destination
  namespace: marriott-production
spec:
  host: backend.marriott-production.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: blue
    - name: v2
      labels:
        version: green
