apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: backend-route
  namespace: marriott-production
spec:
  gateways:
    - marriott-gateway
  hosts:
    - backend.marriott-production.svc.cluster.local
  http:
    - route:
        - destination:
            host: backend.marriott-production.svc.cluster.local
            subset: v2
          weight: 100
